# WARNING!!!
# Before you close this file, ANSWER this question:
# What data are you analyzing?
# If you are not sure, or your answer is 16S, ITS, 
# bacteria, fungi, microbial, blabla, as long as you have
# a slight moment of hesitation, wait and read the comment
# part below (or ask someone from metaEE, buy him/her a 
# coffee too).
 
primers:
    fw: GTGARTCATCRARTYTTTG
    rv: CCTSCSCTTANTDATATGC
trim:
    fw: 0
    rv: 0
database: #path/to/burst/database
    acx: /hwfssz1/ST_META/EE/bin/database/ee_its_database.acx
    edx: /hwfssz1/ST_META/EE/bin/database/ee_its_database.edx
    tax: /hwfssz1/ST_META/EE/bin/database/ee_its_taxonomy.txt
align:
    mode: BEST 
    id: 0.97
qc:
    truncLen: 200
# Align parameters for Burst:   
# Choose from FORAGE, ALLPATHS, BEST, or other mode option in Burst

######################################################################
 ### Uncomment one of the following section for other primer sets ###
  ##            Or add the primers of your choice                 ##
   ################################################################


#############
### FUNGI ###
#############

## DATABASE FOR FUNGI - UNITE #################################################
#database: #path/to/burst/database
#    acx: /hwfssz1/ST_META/EE/bin/database/ee_its_database.acx
#    edx: /hwfssz1/ST_META/EE/bin/database/ee_its_database.edx
#    tax: /hwfssz1/ST_META/EE/bin/database/ee_its_taxonomy.txt
###############################################################################

## ITS1 #######################################################################
## This is the primer set used in Leho 2016 New Phytologist paper #############
## The conservative SSU region is trimmed off. ################################
#primers:
#    fw: GGTCATTTAGAGGAAGTAAAAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATT
#    rv: TTYRCKRCGTTCTTCATCG
#trim:
#    fw: 0
#    rv: 0
###############################################################################
   
## ITS2 #######################################################################
## This is the primer set used in Leho 2016 New Phytologist paper #############
## There is a 60 bp variable region (probably LSU) starting from the reverse  #
## primer. But this 60 bp region is NOT in UNITE, trimmed off by ITSx.        #
## Thus we need to trim off the 41 bp following the reverse primer,           #
## in order to perform global alignment.                                      #
#primers:
#    fw: GTGARTCATCRARTYTTTG
#    rv: CCTSCSCTTANTDATATGC
#trim:
#    fw: 0
#    rv: 41
###############################################################################

##################
### PROKARYOTE ###
##################

### Most of the 16S primer sets are adopted from the paper https://doi.org/10.1093/nar/gks808
### Most of the primers are designed for Bacteria, not for Archea.

## DATABASE FOR 16S - SILVA ###################################################
#database: #path/to/burst/database                                            #
#    acx: /hwfssz1/ST_META/EE/bin/database/silva_132_97_16S.acx               #
#    edx: /hwfssz1/ST_META/EE/bin/database/silva_132_97_16S.edx               #
#    tax: /hwfssz1/ST_META/EE/bin/database/silva_132_97_16S.txt               #
###############################################################################

## DATABASE FOR 16S - GREENGENE ###############################################
#database: #path/to/burst/database                                            #
#    acx: /hwfssz1/ST_META/EE/bin/database/gg_138_97_16S.acx                  #
#    edx: /hwfssz1/ST_META/EE/bin/database/gg_138_97_16S.edx                  #
#    tax: /hwfssz1/ST_META/EE/bin/database/gg_138_97_16S.txt                  #
###############################################################################

## 16S V4 #####################################################################
##                                                                            #
#primers:
#    fw: CAGCMGCCGCGGTAATWC
#    rv: GACTACHVGGGTATCTAATCC
#trim:
#    fw: 0
#    rv: 0
###############################################################################

## 16S V1-V3 ##################################################################
##                                                                            #
#primers:
#    fw: AGAGTTTGATYMTGGCTCAG
#    rv: ATTACCGCGGCTGCTGGC
#trim:
#    fw: 0
#    rv: 0
###############################################################################

## 16S V3-V4 ##################################################################
##                                                                            #
#primers:
#    fw: CCTACGGGRSGCAGCAG
#    rv: GGACTACCAGGGTATCTAATCCTGTT
#trim:
#    fw: 0
#    rv: 0
###############################################################################

## 16S V3-V5 ##################################################################
##                                                                            #
#primers:
#    fw: TACGGRAGGCAGCAG
#    rv: CGTCAATTCMTTTGAGTT
#trim:
#    fw: 0
#    rv: 0
###############################################################################

## 16S V4-V6 ##################################################################
##                                                                            #
#primers:
#    fw: CAGCMGCCGCGGTAATWC
#    rv: TCACGRCACGAGCTGACGAC
#trim:
#    fw: 0
#    rv: 0
###############################################################################

## 16S V5-V6 ##################################################################
##                                                                            #
#primers:
#    fw: GGMTTAGATACCCBDGTA
#    rv: GGGTYKCGCTCGTTR
#trim:
#    fw: 0
#    rv: 0
###############################################################################
